### ISSUE TITLE
Error scanning target systems after changing interface

### ISSUE THREAD

**Issue by treierp** [Minary/Minary#18]
If Minary is operated with two network cards, the scan of the target systems fails with a null pointer exception if the interface is changed before the scan.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Minary.Form.ArpScan.Presentation.ArpScan.SetArpScanGuiOnStarted()
   at Minary.Form.ArpScan.Presentation.ArpScan.StartArpScan(Action onScanDoneCallback)
   at Minary.Form.ArpScan.Presentation.ArpScan.BT_Scan_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)

**Comment by rubenunteregger** [comment]
@treierp I tried to reproduce the bug but unfortunately withouth success. I have 2 NICs, one wired the other wifi.

My procedure was:
  - Start Minary 
  - Select the other NIC (GW IP, GW MAC, Vendor and Netrange change their values)
  - Open ARP-Scanner by clicking on the according icon (the wifi icon with the "i")
  - Start ARP scan

This works fine and no Exception was thrown. After that I closed the ARP scan GUI. 
In the main GUI I did the same steps and checks for the other NIC and also there nothing happened.

Can you please give me more detailed instructions and tell me how exactely you manage to trigger this Exception?
